name: PR Commit
on:
  pull_request:
    branches: [main]
jobs:
  prettier:
    name: Prettier Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install Node packages
        run: npm install
      - name: Check code format
        run: npm run format:check

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install Node packages
        run: npm install
      - name: Lint source code
        run: npm run lint:check
      - name: Lint commits
        run: npx commitlint --verbose --from=origin/main

  build:
    name: Build applications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install Node packages
        run: npm install
      - name: Build applications
        run: npm run build
